language: node_js
node_js:
    - '10'
    - '11'
    - '12'
    - '13'
    - '14'
script:
    - npm install webpack@4.39.0
    - npm test
    - npm install webpack@latest
    - npm test
after_success:
    - 'npm install coveralls && npm install nyc && ./node_modules/.bin/nyc report --temp-directory=coverage --reporter=text-lcov | ./node_modules/.bin/coveralls'
notifications:
    webhooks:
        urls:
            - 'https://www.travisbuddy.com/'
        on_success: never
        on_failure: always
        on_start: never
        on_cancel: never
        on_error: never
